---
services: docker

language: python
python:
  - 3.6
cache: pip

install:
  - pip install -r requirements.txt

before_script:
  - cd ..
  - mv ansible-role-base hadrienpatte.base
  - cd hadrienpatte.base

script:
  - yamllint .
  - ansible-lint -v
  - flake8 -v
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
